<a href="https://colab.research.google.com/github/julianovale/PO450/blob/main/0001_VotacaoDeputados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [157]:
# Importando as bibliotecas necessárias

import pandas as pd

In [158]:
# Lendo dados diretamente no site da Câmara

url2019 = 'http://dadosabertos.camara.leg.br/arquivos/votacoesVotos/csv/votacoesVotos-2019.csv'
votacoes2019 = pd.read_csv(url2019, sep=';')
url2020 = 'http://dadosabertos.camara.leg.br/arquivos/votacoesVotos/csv/votacoesVotos-2020.csv'
votacoes2020 = pd.read_csv(url2020, sep=';')
url2021 = 'http://dadosabertos.camara.leg.br/arquivos/votacoesVotos/csv/votacoesVotos-2021.csv'
votacoes2021 = pd.read_csv(url2021, sep=';')

In [159]:
# Concatenando os dados num único DF

frames = [votacoes2019, votacoes2020, votacoes2021]
votacoes = pd.concat(frames)
votacoes

       idVotacao  ...                                   deputado_urlFoto
0      16526-506  ...  http://www.camara.gov.br/internet/deputado/ban...
1      16526-506  ...  http://www.camara.gov.br/internet/deputado/ban...
2      16526-506  ...  http://www.camara.gov.br/internet/deputado/ban...
3      16526-506  ...  http://www.camara.gov.br/internet/deputado/ban...
4      16526-506  ...  http://www.camara.gov.br/internet/deputado/ban...
...          ...  ...                                                ...
10015  2269710-9  ...  http://www.camara.gov.br/internet/deputado/ban...
10016  2269710-9  ...  http://www.camara.gov.br/internet/deputado/ban...
10017  2269710-9  ...  http://www.camara.gov.br/internet/deputado/ban...
10018  2269710-9  ...  http://www.camara.gov.br/internet/deputado/ban...
10019  2269710-9  ...  http://www.camara.gov.br/internet/deputado/ban...

[290689 rows x 12 columns]

In [160]:
# Verificando os nomes das colunas

votacoes.columns.ravel()

array(['idVotacao', 'uriVotacao', 'dataHoraVoto', 'voto', 'deputado_id',
       'deputado_uri', 'deputado_nome', 'deputado_siglaPartido',
       'deputado_uriPartido', 'deputado_siglaUf',
       'deputado_idLegislatura', 'deputado_urlFoto'], dtype=object)

In [161]:
# Excluindo colunas desnecessárias e reiniciando os índices

df = votacoes[['idVotacao', 'voto', 'deputado_id','deputado_nome', 'deputado_siglaPartido','deputado_siglaUf']]
df = df.reset_index(drop=True)
df

        idVotacao voto  ...  deputado_siglaPartido deputado_siglaUf
0       16526-506  Não  ...                     PL               BA
1       16526-506  Não  ...                    PSL               SP
2       16526-506  Não  ...                   PSDB               BA
3       16526-506  Não  ...                   NOVO               SP
4       16526-506  Não  ...                     PP               GO
...           ...  ...  ...                    ...              ...
290684  2269710-9  Sim  ...                     PT               MA
290685  2269710-9  Sim  ...                     PT               BA
290686  2269710-9  Sim  ...          SOLIDARIEDADE               MG
290687  2269710-9  Sim  ...                     PL               MG
290688  2269710-9  Sim  ...                     PT               PR

[290689 rows x 6 columns]

In [162]:
# Lendo arquivo de UFs x Regiões Geográficas IBGE

url = 'https://github.com/julianovale/PO450/blob/main/UFxREG.xlsx?raw=true'
ufxreg = pd.read_excel(url)
ufxreg

    COD_IBGE                    UF SIGLA_UF REG
0         12                 Acre        AC   N
1         27              Alagoas        AL  NE
2         13              Amazonas       AM   N
3         16                Amapá        AP   N
4         29                 Bahia       BA  NE
5         23                Ceará        CE  NE
6         53      Distrito Federal       DF  CO
7         32        Espírito Santo       ES  SE
8         52                 Goiás       GO  CO
9         21             Maranhão        MA  NE
10        31          Minas Gerais       MG  SE
11        50    Mato Grosso do Sul       MS  CO
12        51           Mato Grosso       MT  CO
13        15                 Pará        PA   N
14        25              Paraíba        PB  NE
15        26           Pernambuco        PE  NE
16        22                 Piauí       PI  NE
17        41                Paraná       PR   S
18        33        Rio de Janeiro       RJ  SE
19        24  Rio Grande do Norte        RN  NE
20        11              Rondônia       RO   N
21        14              Roraima        RR   N
22        43     Rio Grande do Sul       RS   S
23        42        Santa Catarina       SC   S
24        28               Sergipe       SE  NE
25        35             São Paulo       SP  SE
26        17            Tocantins        TO   N

In [163]:
# Inserindo informação de Regiões no DF de votações, excluindo colunas desnecessárias,
# ordenando o DF e reiniciando os índices

df = df.merge(ufxreg,left_on='deputado_siglaUf',right_on='SIGLA_UF')
df = df[['idVotacao', 'voto', 'deputado_id','deputado_nome', 'deputado_siglaPartido','deputado_siglaUf','REG']]
df.sort_values(by=['idVotacao','deputado_id'],inplace=True)
df = df.reset_index(drop=True)
df

          idVotacao voto  ...  deputado_siglaUf REG
0       1198512-250  Sim  ...                CE  NE
1       1198512-250  Sim  ...                ES  SE
2       1198512-250  Sim  ...                SP  SE
3       1198512-250  Sim  ...                PI  NE
4       1198512-250  Sim  ...                SE  NE
...             ...  ...  ...               ...  ..
290684   946625-101  Não  ...                SP  SE
290685   946625-101  Não  ...                RN  NE
290686   946625-101  Não  ...                SC   S
290687   946625-101  Sim  ...                RR   N
290688   946625-101  Não  ...                SC   S

[290689 rows x 7 columns]

In [164]:
# Verificando NaN

df.isna().sum()

idVotacao                0
voto                     0
deputado_id              0
deputado_nome            0
deputado_siglaPartido    0
deputado_siglaUf         0
REG                      0
dtype: int64

In [165]:
# Verificando tipos possíveis de voto

df.groupby('voto').count()

           idVotacao  deputado_id  ...  deputado_siglaUf     REG
voto                               ...
Abstenção        662          662  ...               662     662
Artigo 17        597          597  ...               597     597
Não           141735       141735  ...            141735  141735
Obstrução       8539         8539  ...              8539    8539
Sim           139156       139156  ...            139156  139156

[5 rows x 6 columns]