<a href="https://colab.research.google.com/github/julianovale/PO450/blob/main/0003_Seade_Covid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
# importando bibliotecas

import pandas as pd

In [13]:
# lendo dados da seade

bases = ['01_populacao.csv', '02_mortalidadeinfantil.csv', '03_obitos.csv', '04_PIB.csv', 
         '05_valoradicionado.csv', '06_consumoenergiaeletrica.csv', '07_veiculos.csv', 
         '08_nascidosvivos.csv', '09_leitosinternacao.csv', '10_profissionaissaude.csv', 
         '11_empregosformais.csv', '12_rendaempregos.csv', '13_idhdimensoes.csv', 
         '14_rendapercapita.csv', '15_agualixoesgosto.csv']

url = 'https://raw.githubusercontent.com/julianovale/PO450/main/seade/'

for i in range(len(bases)):
  if i == 0:
    df = pd.read_csv(url+bases[i], sep = ';', encoding= 'Windows-1252')
  else:
    df = df.merge(pd.read_csv(url+bases[i], sep = ';', encoding= 'Windows-1252'),left_on='Cód. IBGE',right_on='Cód. IBGE')

In [15]:
df

            Localidades_x  ...  Esgoto Sanitário - Nível de Atendimento - Censo Demográfico (Em %)
0              Adamantina  ...                                              99,03
1                  Adolfo  ...                                              95,93
2                   Aguaí  ...                                              98,87
3          Águas da Prata  ...                                              87,99
4        Águas de Lindóia  ...                                              90,33
..                    ...  ...                                                ...
640  Vista Alegre do Alto  ...                                              99,74
641        Vitória Brasil  ...                                              97,19
642            Votorantim  ...                                              95,94
643           Votuporanga  ...                                              98,95
644              Zacarias  ...                                              97,02

[645 rows x 123 columns]

In [16]:
df.columns.ravel()

array(['Localidades_x', 'Períodos_x', 'População ',
       'População Masculina ', 'População Feminina ', 'Razão de Sexos ',
       'População Urbana ', 'População Rural ',
       'Grau de Urbanização (Em %)', 'Cód. IBGE', 'Localidades_y',
       'Períodos_y',
       'Taxa de Mortalidade Infantil (Por mil nascidos vivos)',
       'Taxa de Mortalidade Neonatal Precoce (Por mil nascidos vivos)',
       'Taxa de Mortalidade Neonatal (Por mil nascidos vivos)',
       'Taxa de Mortalidade Pós Neonatal (Por mil nascidos vivos)',
       'Taxa de Mortalidade Neonatal Tardia (Por mil nascidos vivos)',
       'Localidades_x', 'Períodos_x',
       'Óbitos Gerais (por local de residência) ',
       'Taxa de Mortalidade Geral (por local de residência) (Por mil habitantes)',
       'Óbitos da População de 15 a 34 Anos ',
       'Taxa de Mortalidade da População de 15 a 34 Anos (Por cem mil habitantes nessa faixa etária)',
       'Óbitos da População de 60 Anos e Mais ',
       'Taxa de Mortalidade da População de 60 Anos e Mais (Por cem mil habitantes nessa faixa etária)',
       'Localidades_y', 'Períodos_y', 'PIB (Em mil reais correntes)',
       'PIB per Capita (Em reais correntes)',
       'Participação no PIB do Estado (Em %)', 'Localidades_x',
       'Períodos_x', 'Valor Adicionado Total (Em mil reais correntes)',
       'Valor Adicionado da Administração Pública (Em mil reais correntes)',
       'Valor Adicionado na Indústria (Em mil reais correntes)',
       'Valor Adicionado dos Serviços (Em mil reais correntes)',
       'Valor Adicionado da Agropecuária (Em mil reais correntes)',
       'Impostos sobre Produtos Líquidos de Subsídios (Em mil reais correntes)',
       'Participação da Administração Pública no Total do Valor Adicionado (Em %)',
       'Participação da Indústria no Total do Valor Adicionado (Em %)',
       'Participação dos Serviços no Total do Valor Adicionado (Em %)',
       'Participação da Agropecuária no Total do Valor Adicionado (Em %)',
       'Localidades_y', 'Períodos_y',
       'Consumo de Energia Elétrica - Total (Em MWh)',
       'Consumo de Energia Elétrica - Industrial (Em MWh)',
       'Consumo de Energia Elétrica -  Comércio e Serviços (Em MWh)',
       'Consumo de Energia Elétrica - Rural (Em MWh)',
       'Consumo de Energia Elétrica - Residencial (Em MWh)',
       'Consumo de Energia Elétrica - Iluminação e Serviços Públicos e Outros (Em MWh)',
       'Localidades_x', 'Períodos_x', 'Frota de Veículos - Total ',
       'Número de Habitantes por Total de Veículos ',
       'Frota de Automóveis ', 'Número de Habitantes por Automóvel ',
       'Frota de Ônibus ', 'Frota de Caminhões ', 'Frota de Reboques ',
       'Frota de Motocicletas e Assemelhados ',
       'Frota de Microônibus e Camionetas ',
       'Frota de Veículos de Outro Tipo ', 'Localidades_y', 'Períodos_y',
       'Nascidos Vivos de Mães com Menos de 18 Anos (Em %)',
       'Mães que fizeram Sete e Mais Consultas de Pré-Natal (Em %)',
       'Partos Cesáreos (Em %)',
       'Nascimentos de Baixo Peso (menos de 2,5kg) (Em %)',
       'Gestações Pré-Termo (Em %)', 'Localidades_x', 'Períodos_x',
       'Leitos de Internação ',
       'Leitos de Internação (Coeficiente por mil habitantes)',
       'Leitos SUS ', 'Leitos SUS (Coeficiente por mil habitantes)',
       'Localidades_y', 'Períodos_y',
       'Auxiliares de Enfermagem Registrados no COREN/SP ',
       'Auxiliares de Enfermagem Registrados no COREN/SP (Coeficiente por mil habitantes)',
       'Dentistas Registrados no CRO/SP ',
       'Dentistas Registrados no CRO/SP (Coeficiente por dois mil habitantes)',
       'Enfermeiros Registrados no COREN/SP ',
       'Enfermeiros Registrados no COREN/SP (Coeficiente por mil habitantes)',
       'Fonoaudiólogos registrados no CRFa/SP ',
       'Fonoaudiólogos registrados no CRFa/SP (Coeficiente por mil habitantes)',
       'Médicos Registrados no CRM/SP ',
       'Médicos Registrados no CRM/SP (Coeficiente por mil habitantes)',
       'Psicólogos Registrados no CRP - 6ª Região [Série interrompida] ',
       'Psicólogos Registrados no CRP - 6ª Região (Coeficiente por mil habitantes) [Série interrompida] (Coeficiente por mil habitantes)',
       'Técnicos de Enfermagem Registrados no COREN/SP ',
       'Técnicos de Enfermagem Registrados no COREN/SP (Coeficiente por mil habitantes)',
       'Técnicos de Prótese Dentária Registrados no CRO/SP ',
       'Técnicos de Prótese Dentária Registrados no CRO/SP (Coeficiente por dois mil habitantes)',
       'Localidades_x', 'Períodos_x', 'Empregos Formais ',
       'Empregos Formais de Homens ', 'Empregos Formais de Mulheres ',
       'Localidades_y', 'Períodos_y',
       'Rendimento Médio do Total de Empregos Formais (Em reais correntes)',
       'Rendimento Médio dos Empregos Formais da Agricultura, Pecuária, Produção Florestal, Pesca e Aquicultura (Em reais correntes)',
       'Rendimento Médio dos Empregos Formais da Indústria (Em reais correntes)',
       'Rendimento Médio dos Empregos Formais da Construção (Em reais correntes)',
       'Rendimento Médio dos Empregos Formais do Comércio Atacadista e Varejista e do Comércio e Reparação de Veículos Automotores e Motocicletas (Em reais correntes)',
       'Rendimento Médio dos Empregos Formais dos Serviços (Em reais correntes)',
       'Localidades_x', 'Períodos_x',
       'Índice de Desenvolvimento Humano Municipal - IDHM ',
       'Índice de Desenvolvimento Humano Municipal - IDHM - Ranking dos Municípios ',
       'Índice de Desenvolvimento Humano Municipal - IDHM Longevidade ',
       'Índice de Desenvolvimento Humano Municipal - IDHM Educação ',
       'Índice de Desenvolvimento Humano Municipal - IDHM Renda ',
       'Localidades_y', 'Períodos_y',
       'Renda per Capita - Censo Demográfico (Em reais correntes)',
       'Domicílios Particulares com Renda per Capita até 1/2 Salário Mínimo - Censo Demográfico (Em %)',
       'Domicílios Particulares com Renda per Capita até 1/4 do Salário Mínimo - Censo Demográfico (Em %)',
       'Localidades', 'Períodos',
       'Abastecimento de Água - Nível de Atendimento - Censo Demográfico (Em %)',
       'Coleta de Lixo - Nível de Atendimento - Censo Demográfico (Em %)',
       'Esgoto Sanitário - Nível de Atendimento - Censo Demográfico (Em %)'],
      dtype=object)

In [17]:
df.isna().sum()

Localidades_x                                                              0
Períodos_x                                                                 0
População                                                                  0
População Masculina                                                        0
População Feminina                                                         0
                                                                          ..
Localidades                                                                0
Períodos                                                                   0
Abastecimento de Água - Nível de Atendimento - Censo Demográfico (Em %)    0
Coleta de Lixo - Nível de Atendimento - Censo Demográfico (Em %)           0
Esgoto Sanitário - Nível de Atendimento - Censo Demográfico (Em %)         0
Length: 123, dtype: int64